!******************************************************************************************************
! Ledicia Díaz Lago
! Physical Materials Simulation 2018/2019
!
! RUN_MANY_MD (launcher / driver)
!
! Goals:
! - Runs the MD simulation multiple times (independent runs).
! - Creates one output directory per run:
!     outputs/run_0001, outputs/run_0002, ...
! - Writes outputs/runs.txt with the list of run directories (for simulation_results).
!
! - "Independent" runs here means independent *output folders*.
!   In case of wanting statistically independent trajectories, one should also randomize the initial velocities
!   (or regenerate outputs/rv_init.dat per run).
!
! Default number of runs:
! - n_runs = 10  (coherent default for estimating mean/std across runs)
!******************************************************************************************************
program run_many_md

  use define_precision, only: int_kind
  use md_simulation,    only: run_md_simulation
  implicit none

  integer(kind=int_kind), parameter :: n_runs_default = 10_int_kind

  character(len=*), parameter :: base_out_dir = 'outputs'
  character(len=*), parameter :: run_prefix   = 'run_'
  character(len=*), parameter :: runs_list    = 'outputs/several_runs.txt'

  integer(kind=int_kind) :: n_runs, i, ierr, n_ok, n_fail
  character(len=512) :: out_dir
  integer :: iu, ios

  ! -----------------------
  ! Choose how many runs to launch
  ! -----------------------
  n_runs = n_runs_default

  ! -----------------------
  ! Open runs.txt (overwrite) and write header
  ! -----------------------
  iu = 90
  open(iu, file=runs_list, status='replace', action='write', iostat=ios)
  if (ios /= 0) stop 'run_many_md(): cannot open outputs/runs.txt for writing.'

  write(iu,'(a)') '# List of MD run output directories (one per line)'
  write(iu,'(a)') '# Generated by run_many_md.f90'

  n_ok   = 0_int_kind
  n_fail = 0_int_kind

  ! -----------------------
  ! Launch runs
  ! -----------------------
  do i = 1_int_kind, n_runs

    out_dir = run_dir_name(base_out_dir, run_prefix, i)

    ! Make sure the directory exists (best effort).
    call ensure_dir_exists(trim(out_dir), ierr)
    if (ierr /= 0_int_kind) then
      n_fail = n_fail + 1_int_kind
      write(*,'(a,1x,a)') 'run_many_md: could not create directory:', trim(out_dir)
      cycle
    end if

    ! Run MD (this will write into out_dir: rva.dat, instantaneous_energies.dat, means.dat, etc.)
    call run_md_simulation(trim(out_dir), ierr)

    if (ierr == 0_int_kind) then
      n_ok = n_ok + 1_int_kind
      write(iu,'(a)') trim(out_dir)      ! Important for simulation_results
      write(*,'(a,i0,a,1x,a)') 'run_many_md: run ', i, ' OK ->', trim(out_dir)
    else
      n_fail = n_fail + 1_int_kind
      write(*,'(a,i0,a,i0)') 'run_many_md: run ', i, ' FAILED, ierr=', ierr
      ! We do NOT add failed runs to runs.txt, so simulation_results will only aggregate valid ones.
    end if

  end do

  close(iu)

  write(*,'(a)') '------------------------------------------------------------'
  write(*,'(a,i0)') 'run_many_md: requested runs = ', n_runs
  write(*,'(a,i0)') 'run_many_md: successful runs = ', n_ok
  write(*,'(a,i0)') 'run_many_md: failed runs      = ', n_fail
  write(*,'(a)') 'run_many_md: wrote outputs/runs.txt for simulation_results.'
  write(*,'(a)') '------------------------------------------------------------'

contains

  ! ------------------------------------------------------------
  ! Build run directory name:
  !   outputs/run_0001, outputs/run_0002, ...
  ! ------------------------------------------------------------
  pure function run_dir_name(base, prefix, idx) result(d)
    character(len=*), intent(in) :: base, prefix
    integer(kind=int_kind), intent(in) :: idx
    character(len=512) :: d
    character(len=32)  :: s

    write(s,'(i4.4)') idx
    d = trim(base)//'/'//trim(prefix)//trim(s)
  end function run_dir_name


  ! ------------------------------------------------------------
  ! Ensure directory exists (best effort).
  ! Why important:
  ! - MD writes multiple files; if the folder doesn't exist, OPEN will fail and the run will error.
  !
  ! Implementation:
  ! - Uses execute_command_line() which is Fortran 2008 and supported by most compilers.
  ! - On Windows you may need: "mkdir <dir>" also works, but quoting rules differ.
  ! ------------------------------------------------------------
  subroutine ensure_dir_exists(dir, ierr)
    character(len=*), intent(in) :: dir
    integer(kind=int_kind), intent(out) :: ierr

    logical :: ex
    integer :: cmd_stat

    ierr = 0_int_kind

    inquire(file=trim(dir), exist=ex)
    if (ex) return

    cmd_stat = 0
    call execute_command_line('mkdir -p "'//trim(dir)//'"', exitstat=cmd_stat)

    if (cmd_stat /= 0) then
      ierr = 1_int_kind
      return
    end if

    inquire(file=trim(dir), exist=ex)
    if (.not. ex) ierr = 1_int_kind
  end subroutine ensure_dir_exists

end program run_many_md
